language: ruby
rvm:
- 2.2.3
cache: bundler
script:
- bundle exec rake
- bundle exec rake deploy-gh-pages
env:
  global:
  - GH_REF: github.com/increments/qiita-team-services.git
  - secure: pdRvHR22U3Se5MuJyOLqdAKUl2xtWbTsTsARNK/i19/yAe7ZjLJVMdFurNmTLz1epGFC4ruNjklJZtnPYy/CXiQVJHb8bJGAaqKNJFjS6cOLCVxax8HKtEdTb6o4qYnIudh7UPSFsVi2rJ8WYT7Rr3gRiHU0TXpvNDvf51DBAaxgoMHqUUI0LvXMQEFLf06dpuR402C9V1uZar5OqMyOV5pTtcgSIQDpdRUOwYdsasuoftgf4LAuLE4zpQJVnbltcPaYV94g8YG6nWg/CiaPMLC8a54BretyGmUKhj1w1e3aG+z9dT5JuFrhjO6jyUi/Sq8b9tV9iyb/sEbsS5A2H5BiNnzdmv9nQCgT3hfSiuB/sphAnaU5YNNcTlLGAVESkIb2AWS9AWB5NeeXBrCaY8d3vVATQTSSRBnJzlArIx9xrolM4wITML9F2FPj572gdvLA30u9d1/pehIMEc9r5n9I0BtGSAiLw7FTRWNzakKB1zOZN/WCgsVrbfLjhTfM8rPp/eijbyehaqOzxcT2FC21XNQhGGH3UyyCwKWt3MYxj1ACivkwnK7IZjFvcLL32u8Jv66CRskedQ0vdNkNmu9KEF+Z8rAS/31NBYGFcUx61ofi7zSO9axfrOos8QScmn+shFgJd7iQC/iwq0K+Wp+7vmpzOnNmxD+PFra8oc8=
