language: ruby
rvm:
  - 2.2.3
cache:
  directories: vendor/bundle
script:
  - bundle exec rake
  - bundle exec rake deploy-gh-pages
env:
  global:
    - GH_REF: github.com/increments/qiita-team-services.git
    - secure: czpqXrO5AZUbvDRLmVb8i8wbTwzGX07pa9t5yu/byGEyeKMNsSvXf+bTep6tuKTf84+Axn0jhSxqjzyZtY0Dpz4z5MzPB4E6TXsqYSXE/fUqFsszXvuOQiT653ryV1KuaA4nNVh/0r9udN26ijmgWhqXth7V0IhPDsegWm0bFfppPWu1+VE02L4t+mN1gER3hHheI8B8MTFkiYyuzcEM6YA4r8dG6h6ZG2aQX54Zv8+Sd+tOy30rD4bh97kxgCgmXudHoZQJCQoESeg0iPme5cGHXC5o13NO5iuUyWCB9FFHpc8eit+hUGwVGwI5HVVGi/kInN6JVMHbjaIWWhnCrK+1xkIotU4zIGfElyETa2NffuvtfZ/dHcga0DPlpQnwR4iZAFMIV7eqYjDXDZNY5+khugnuWPQeZsh7Qy30msmsodm9H8gKLny6CiRPBve1RkOqauVxaV30XbchfH7eL1ADnVeCJVfenXOw7WfAKvGmUMZ5O0SSbJnpiT7RgJlbfm/9JYPVKrDiAkfiFTomLGJv19ZM/jsqxsugI6s0rSpTArzst/Rz27wqkfg/LZ+Gfe44LYbvwPhAAXD/cDDz+LePYvbnzkqjPHrIpe1N8e7Z3urwStDkas+wz4pylWQnrZwBpi4MtU+WQeaMkemtUJGpnjEeaWnJ7i9A4eR5oew=
